package com.callrecorder.payamgostar.wcf;


//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development 
//
//---------------------------------------------------


import com.callrecorder.payamgostar.Logger;

import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;

import java.util.List;


public class BasicHttpBinding_ICall {
    interface IWcfMethod {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }

    public String url = null;

    int timeOut = 60000;
    public List<HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;

    //public BasicHttpBinding_ICall() {
    //}

    public BasicHttpBinding_ICall(String serverName) {
        if(serverName.endsWith("/")){
            url = serverName + "Services/ICall.svc/ICall";
        }else{
            url = serverName + "/Services/ICall.svc/ICall";
        }
    }

    public BasicHttpBinding_ICall(IServiceEvents callback) {
        this.callback = callback;
    }

    public BasicHttpBinding_ICall(IServiceEvents callback, String url) {
        this.callback = callback;
        this.url = url;
    }

    public BasicHttpBinding_ICall(IServiceEvents callback, String url, int timeOut) {
        this.callback = callback;
        this.url = url;
        this.timeOut = timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport() {
        try {
            java.net.URI uri = new java.net.URI(url);
            if (uri.getScheme().equalsIgnoreCase("https")) {
                int port = uri.getPort() > 0 ? uri.getPort() : 443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            } else {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url, timeOut);
            }

        } catch (java.net.URISyntaxException e) {
        }
        return null;
    }

    protected ExtendedSoapSerializationEnvelope createEnvelope() {
        ExtendedSoapSerializationEnvelope envelope = new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }

    protected java.util.List sendRequest(String methodName, ExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        if (transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        } else {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE) transport).call(methodName, envelope, httpHeaders, null, profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj, java.lang.Object source, String resultName, ExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception {
        if (source == null) {
            return null;
        }
        if (source instanceof SoapPrimitive) {
            SoapPrimitive soap = (SoapPrimitive) source;
            if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        } else {
            SoapObject soap = (SoapObject) source;
            if (soap.hasProperty(resultName)) {
                java.lang.Object j = soap.getProperty(resultName);
                if (j == null) {
                    return null;
                }
                java.lang.Object instance = __envelope.get(j, destObj, false);
                return instance;
            } else if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        }

        return null;
    }


    public Long RegisterFullCall(final Enums.PhoneCallType phoneCallType, final String phoneNumber, final String lineNumber, final String extension, final java.util.Date startDate, final java.util.Date endDate, final String tsKey, final String mediaFile) throws java.lang.Exception {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Long) execute(new IWcfMethod() {
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "RegisterFullCall");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "phoneCallType";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(phoneCallType != null ? phoneCallType.toString() : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "phoneNumber";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(phoneNumber != null ? phoneNumber : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "lineNumber";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(lineNumber != null ? lineNumber : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "extension";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(extension != null ? extension : SoapPrimitive.NullSkip);

                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "startDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(startDate != null ? Helper.getDateTimeFormat().format(startDate) : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "endDate";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(endDate != null ? Helper.getDateTimeFormat().format(endDate) : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "tsKey";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(tsKey != null ? tsKey : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace = "http://tempuri.org/";
                __info.name = "mediaFile";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(mediaFile != null ? mediaFile : SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            public java.lang.Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                SoapObject __soap = (SoapObject) __result;
                java.lang.Object obj = __soap.getProperty("RegisterFullCallResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                    SoapPrimitive j = (SoapPrimitive) obj;
                    return new Long(j.toString());
                } else if (obj != null && obj instanceof Long) {
                    return (Long) obj;
                }
                return null;
            }
        }, "http://tempuri.org/ICall/RegisterFullCall", __profile);
    }

    public android.os.AsyncTask<Void, Void, OperationResult<Long>> RegisterFullCallAsync(final Enums.PhoneCallType phoneCallType, final String phoneNumber, final String lineNumber, final String extension, final java.util.Date startDate, final java.util.Date endDate, final String tsKey, final String mediaFile) {
        return executeAsync(new Functions.IFunc<Long>() {
            public Long Func() throws java.lang.Exception {
                return RegisterFullCall(phoneCallType, phoneNumber, lineNumber, extension, startDate, endDate, tsKey, mediaFile);
            }
        }, "RegisterFullCall");
    }


    protected java.lang.Object execute(IWcfMethod wcfMethod, String methodName, com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception {
        org.ksoap2.transport.Transport __httpTransport = createTransport();
        __httpTransport.debug = enableLogging;
        ExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
        try {
            sendRequest(methodName, __envelope, __httpTransport, profile);

        } finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    Logger.i("requestDump", __httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    Logger.i("responseDump", __httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault) {
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault) __retObj;
            throw convertToException(__fault, __envelope);
        } else {
            return wcfMethod.ProcessResult(__envelope, __retObj);
        }
    }

    protected <T> android.os.AsyncTask<Void, Void, OperationResult<T>> executeAsync(final Functions.IFunc<T> func, final String methodName) {
        return new android.os.AsyncTask<Void, Void, OperationResult<T>>() {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            }

            ;

            @Override
            protected OperationResult<T> doInBackground(Void... params) {
                OperationResult<T> result = new OperationResult<T>();
                try {
                    result.MethodName = methodName;
                    result.Result = func.Func();
                } catch (java.lang.Exception ex) {
                    ex.printStackTrace();
                    result.Exception = ex;
                }
                return result;
            }

            @Override
            protected void onPostExecute(OperationResult<T> result) {
                callback.Completed(result);
            }
        }.execute();
    }

    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault, ExtendedSoapSerializationEnvelope envelope) {
        org.ksoap2.SoapFault newException = fault;

        return newException;
    }
}


