package com.callrecorder.payamgostar.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.2.8.1
//
// Created by Quasar Development 
//
//---------------------------------------------------





public class Enums
{

    public enum PhoneCallType
    {
        
        Incoming(0),
        
        Outgoing(1),

        MissCall(2);
        
        private int code;
        
        PhoneCallType(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }

        public static PhoneCallType fromCode(int intCode){
            switch (intCode){
                case 0:
                    return Incoming;
                case 1:
                    return Outgoing;
                case 2:
                    return MissCall;
            }

            return null;
        }

        public static PhoneCallType fromString(String str)
        {
            if (str.equals("Incoming"))
                return Incoming;
            if (str.equals("Outgoing"))
                return Outgoing;
            if (str.equals("MissCall"))
                return MissCall;
		    return null;
        }
    }

}